#=== 配置文件 ====
spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false

#=== Redis配置 ====
  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 100
        #最大阻塞等待时间(负数表示没限制)
        max-wait: 2000
        #最大空闲
        max-idle: 500
        #最小空闲
        min-idle: 8
    #连接超时时间
    timeout: 5000

# === JPA配置 ====
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

#=================Mybatis配置=========================
# 别名配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  # xml扫描位置mybatis:
  mapper-locations: classpath*:mapper/*.xml

#=================Logback日志配置=========================
logging:
  config: classpath:logback-spring.xml
